name: "SonarCloud ↔ GitHub Sync"
description: "Synchronize issues bidirectionally between SonarCloud and GitHub. Requires 'issues: write' permission in your workflow job."
author: "Gorton218"

inputs:
  sonar_project:
    description: "SonarCloud project key (e.g., 'my-org_my-project')"
    required: true
  issue_types:
    description: "Comma-separated list of issue types to sync"
    required: false
    default: "BUG,VULNERABILITY,CODE_SMELL"
  dry_run:
    description: "Preview changes without making modifications"
    required: false
    default: "false"
  log_level:
    description: "Logging level (DEBUG, INFO, WARNING, ERROR, CRITICAL)"
    required: false
    default: "INFO"
  debug:
    description: "Enable debug logging"
    required: false
    default: "false"
  python_version:
    description: "Python version to use"
    required: false
    default: "3.11"
  sonar_token:
    description: "SonarCloud token for authentication"
    required: true
  github_token:
    description: "GitHub token for authentication. The workflow must have 'issues: write' permission to create and close issues."
    required: false
    default: "${{ github.token }}"

outputs:
  sync_status:
    description: "Sync operation status"
    value: ${{ steps.sync.outputs.status }}

runs:
  using: composite
  steps:
    - name: Setup Python
      uses: actions/setup-python@v5
      with:
        python-version: ${{ inputs.python_version }}

    - name: Cache pip
      uses: actions/cache@v4
      with:
        path: ~/.cache/pip
        key: ${{ runner.os }}-pip-${{ inputs.python_version }}-${{ hashFiles(format('{0}/pyproject.toml', github.action_path)) }}
        restore-keys: |
          ${{ runner.os }}-pip-${{ inputs.python_version }}-
          ${{ runner.os }}-pip-

    - name: Install sonarcloud-sync
      shell: bash
      working-directory: ${{ github.action_path }}
      run: |
        set -euo pipefail
        python -m pip install --upgrade pip
        pip install .

    - name: Run sync
      id: sync
      shell: bash
      env:
        SONAR_TOKEN: ${{ inputs.sonar_token }}
        GITHUB_TOKEN: ${{ inputs.github_token }}
      run: |
        set -euo pipefail
        CMD=(sonarcloud-github-sync \
          --sonar-project "${{ inputs.sonar_project }}" \
          --github-repo "${{ github.repository }}" \
          --issue-types "${{ inputs.issue_types }}" \
          --log-level "${{ inputs.log_level }}")
        
        if [ "${{ inputs.dry_run }}" = "true" ]; then
          CMD+=(--dry-run)
        fi
        
        if [ "${{ inputs.debug }}" = "true" ]; then
          CMD+=(--debug)
        fi
        
        echo "Running: ${CMD[*]}"
        "${CMD[@]}"
        exit_code=$?
        
        if [ "$exit_code" -eq 0 ]; then
          echo "status=success" >> "$GITHUB_OUTPUT"
        else
          echo "status=failure" >> "$GITHUB_OUTPUT"
          exit "$exit_code"
        fi
